### ISSUE TITLE
error

### ISSUE THREAD

**Issue by TT-IPIP** [Vital7/GetEmail#34]
2021-07-23 13:46:26|ArchiSteamFarm-631|ERROR|ASF|InitPlugins() 因发生此错误而失败：GetEmail, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
2021-07-23 13:46:26|ArchiSteamFarm-631|ERROR|ASF|InitPlugins() System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'ArchiSteamFarm.Plugins.IBot' from assembly 'ArchiSteamFarm, Version=5.1.1.1, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
System.TypeLoadException: Could not load type 'ArchiSteamFarm.Plugins.IBot' from assembly 'ArchiSteamFarm, Version=5.1.1.1, Culture=neutral, PublicKeyToken=null'.

**Comment by Vital7** [comment]
Hello, try using latest CI build: https://github.com/Vital7/GetEmail/suites/3269917472/artifacts/76139214

**Comment by TT-IPIP** [comment]
thank you very much

**Comment by Vital7** [comment]
You're welcome!
